
openapi: 3.0.0

info:
version: "1.0.0"
title: Test API

servers:
- url: "http://localhost/api/v1"
description: "TrackAPI"

paths:
  /track:
post:
tags:
- hoge機能
summary: "hogeする"
description: "処理概要"
security:
- basicAuth: []
parameters:
- in: header
name: Version
schema:
$ref: "#/components/schemas/Version"
- in: header
name: Auth-Type
schema:
$ref: "#/components/schemas/Auth-Type"
requestBody:
content:
application/json:
schema:
type: object
properties:
data:
type: object
properties:
message:
type: string
maxLength: 100
example:
data:
message: hogehoge
responses:
200:
description: OK
content:
application/json:
schema:
type: object
properties:
data:
type: object
properties:
result:
type: boolean
example:
data:
result: true
404:
description: NG
content:
application/json:
schema:
type: object
properties:
data:
type: object
properties:
result:
type: boolean
example:
data:
result: false

components:
securitySchemes:
BearerAuth:
type: http
scheme: bearer
schemas:
Auth-Type:
description: 権限
type: string
example: user
Version:
description: バージョン
type: string
example: 1
Forwarded-For:
description: クライアントIPアドレス
type: string
example: 127.0.0.1
openapi: 3.0.0
 
info:
version: "1.0.0"
title: Test API
 
servers:
- url: "http://localhost/"
description: "TestAPI"
 
paths:
/hoge:
post:
tags:
- hoge機能
summary: "hogeする"
description: "処理概要"
security:
- basicAuth: []
parameters:
- in: header
name: Version
schema:
$ref: "#/components/schemas/Version"
- in: header
name: Auth-Type
schema:
$ref: "#/components/schemas/Auth-Type"
requestBody:
content:
application/json:
schema:
type: object
properties:
data:
type: object
properties:
message:
type: string
maxLength: 100
example:
data:
message: hogehoge
responses:
200:
description: OK
content:
application/json:
schema:
type: object
properties:
data:
type: object
properties:
result:
type: boolean
example:
data:
result: true
404:
description: NG
content:
application/json:
schema:
type: object
properties:
data:
type: object
properties:
result:
type: boolean
example:
data:
result: false
 
components:
securitySchemes:
BearerAuth:
type: http
scheme: bearer
schemas:
Auth-Type:
description: 権限
type: string
example: user
Version:
description: バージョン
type: string
example: 1
Forwarded-For:
description: クライアントIPアドレス
type: string
example: 127.0.0.1
 